[env:esp32s3-n16r8]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

board_build.flash_mode          = qio
board_build.psram_type          = opi
board_build.memory_type         = qio_opi
board_upload.flash_size         = 16MB
board_build.arduino.memory_type = qio_opi
board_build.partitions          = default_16MB.csv
board_build.f_cpu               = 240000000L

; USB OTG режим — клавиатура работает через этот порт
board_build.extra_flags =
  -D ARDUINO_USB_MODE=0
  -D ARDUINO_USB_CDC_ON_BOOT=0

monitor_speed = 115200
upload_speed  = 921600

build_flags =
  -D BOARD_HAS_PSRAM
  -D CONFIG_ESP_WIFI_ENABLE_WIFI_TX=1
  -D CONFIG_ESP32_WIFI_TX_BUFFER=32
  -Wl,--wrap=ieee80211_raw_frame_sanity_check
  -Wl,--allow-multiple-definition
  -D CORE_DEBUG_LEVEL=4
  -D CONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
  -D CONFIG_BT_NIMBLE_ROLE_CENTRAL_DISABLED=1
  -D CONFIG_BT_NIMBLE_ROLE_OBSERVER_DISABLED=1

lib_deps =
  adafruit/Adafruit GFX Library
  adafruit/Adafruit ST7735 and ST7789 Library
  makuna/RTC @ ^2.3.5
  h2zero/NimBLE-Arduino@^2.1.0
  esp32 @ >=2.0.0
  nrf24/RF24
  mathieucarbou/ESPAsyncWebServer
  crankyoldgit/IRremoteESP8266
  bblanchon/ArduinoJson
  tanakamasayuki/EspUsbHost
  https://github.com/espressif/idf-extra-components.git#master
  adafruit/DHT sensor library
  adafruit/Adafruit Unified Sensor
